# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 135f517efc211b6f0b10ee27465a292cf1489d1ae3a478e8e6746eddf726ea9e10bc3c262dc732629789d2bf450512deaeb0ce1c5c2bff3cac92c35594bf9c64

test:
  secret_key_base: 13a7d54c94b3d1f9bb46fadd835a8d769f9fc8a8250b9761defa5ac2a8328abd647d3377c0c195995906ca607ee618e2487a255261d377a67b94a49511116e10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
